### ISSUE TITLE
Why buffer has settings?

### ISSUE THREAD

**Issue by zidoms** [limetext/text#6]
I don't understand why buffer should have settings which also we can not set parent for them because one buffer may have multiple views.

**Comment by quarnster** [comment]
I don't know, let's remove it and we'll eventually find out if it's actually needed ;)

**Comment by zidoms** [comment]
Also we should move `Word` and `WordR` function to view.

**Comment by zidoms** [comment]
Removed settings from buffer 966115e3fb3a7f0cf0733f272de127786e7c487b.
