### ISSUE TITLE
Cleanup: Parent-child settings OnChange propagation. Is it actually useful?

### ISSUE THREAD

**Issue by quarnster** [limetext/text#8]
The parent-child-relationship [sets up a link](https://github.com/limetext/text/blob/c52812c8d01ff59ebd0925dbd4295d0fdd61136d/settings.go#L73) so that changes in a child-setting will notify the parent that the setting was changed. Though thinking about it now I'm not entirely sure this is of use as OnChangeCallbacks added to the parent (or grand-/grandgrand-/grandgrandgrand-/etc-parent) will not query the child settings item but the parent (or ...) which could either have a different value set or not contain the setting at all. Hence the claim that the value changed isn't true for the ancestors.

Is the OnChangeCallback-propagation actually useful or is it just wasted CPU cycles accomplishing absolutely nothing?

**Comment by quarnster** [comment]
Forgot to add that if it is useful, it should be documented why it's useful so that we won't have to figure it out again should the topic ever come up in the future.

**Comment by zoli** [comment]
> The parent-child-relationship sets up a link so that changes in a child-setting will notify the parent

You are saying this reversed, Changes in parent setting will notify the child and IMO this is necessary.
